### ISSUE TITLE
Enabling CORS for kdu_server and kdu_server alternatives

### ISSUE THREAD

**Issue by anthonycarbone** [MaMazav/webjpip.js#4]
Hi,

In the README you mention its very easy to add the necessary headers to kdu_server messages to enable CORS and expose the headers. What edits do you recommend to do so? I have a full Kakadu licence for V8.0.6.

Also, any open-source alternatives to kdu_server you found useful and worked for webjpip, for instance [OpenJPIP](https://github.com/uclouvain/openjpeg/wiki/OpenJPIP)?

Thanks

Edit:
I'm currently using a node.js proxy which seems to work, but I'd imagine its ideal to forego the proxy altogether and instead have kdu_server enable CORS directly.

**Comment by MaMazav** [comment]
Sorry for missing this issue for so long time. Also I didn't save the change, but as far as I remember it was applied to file src\apps\kdu_server\kdu_serve.cpp or src\apps\kdu_server\kdu_server.cpp. It was just to add two lines for CORS headers (one which you choose which sources are fine, e.g. '*' for everything, and one to consider this header secure for the browser).

**Comment by anthonycarbone** [comment]
Thanks for the reply @MaMazav! All good though, I just saw the rest of the project out with a CORS proxy. Cheers!
